import{isDebug as t,getUserState as e,postTransaction as n,UserState as a}from"./network.js";function animateBackground(t){let e=document.getElementById(t),n=e.getContext("2d");function a(){e.width=window.innerWidth,e.height=window.innerHeight}a(),window.addEventListener("resize",a);let i=Array.from({length:120}).map(()=>({x:Math.random()*e.width,y:Math.random()*e.height,radius:2*Math.random()+1,speed:1.5*Math.random()+.5}));!function t(){n.clearRect(0,0,e.width,e.height),n.fillStyle="white",i.forEach(t=>{n.beginPath(),n.arc(t.x,t.y,t.radius,0,2*Math.PI),n.fill(),t.y+=t.speed,t.y>e.height&&(t.y=0,t.x=Math.random()*e.width)}),requestAnimationFrame(t)}()}function showContent(e,a,i){let o=document.getElementById("play_nav_item"),s=document.getElementById("tasks_nav_item"),l=document.getElementById("cash_out_nav_item");o.textContent=e.bottombar.playItem.title,s.textContent=e.bottombar.tasksItem.title,l.textContent=e.bottombar.withdrawItem.title,document.getElementById("progress").style.display="none",document.getElementById("error-content").style.display="none",document.getElementById("main-content").style.display="block",animateText(0,e.balance.value,"usdt-text","",e.balance.precision),animateText(0,e.reward.coefficient,"coefficient-text"," X"),animateBackground("content-background-stars");let r=document.getElementById("coefficient-menu-item"),c=document.getElementById("usdt-menu-item");r.addEventListener("click",()=>{document.getElementById("earn-nav-item").click()}),c.addEventListener("click",()=>{});let d=document.getElementById("usdt-button");d.textContent=`${e.cashOutPage.btnText} ${e.balance.value.toFixed(e.balance.precision)} USDT`,d.addEventListener("click",function(){if(a.wallet){let o=e.balance.value;e.balance.value>=e.balance.minWithDrawAmount?(async()=>{try{let s=null,l=null;t?(s="1",l="test"):(s=i.id,l=i.username??i.first_name);let r=a.wallet.account,c=(await n(s,l,o,r)).withDrawAmount;e.balance.value-=c,animateText(0,e.balance.value,"usdt-text","",e.balance.precision),d.textContent=`Вывести ${e.balance.value.toFixed(e.balance.precision)} USDT`,requestWithDraw(e.cashOutPage.successWithDrawPostfix,c,e.balance.precision)}catch(m){console.error(m),showError()}})():requestWithDrawInsufficient(e)}else a.openModal()});let m=document.getElementById("proof-button");"ru"==e.language?m.textContent="\uD83D\uDC24 Смотрите выплаты в Telegram. Жми! \uD83D\uDC24":m.textContent="\uD83D\uDC24 See our payouts on Telegram. Click! \uD83D\uDC24",m.addEventListener("click",function(){window.open("https://t.me/flappytappynews")});let u=document.getElementById("transaction-delay-text");u&&(u.textContent=e.cashOutPage.transactionDelayText)}function showWalletConnectedToast(){let t=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>Кошелек подключен</span>
  </div>`;showToast(t)}function requestWithDrawInsufficient(t){let e=`
  <div class="token" style="align: center;">
      <span>${t.cashOutPage.insufficientNotificationText} ${t.balance.minWithDrawAmount} USDT</span>
  </div>`;showToast(e)}function requestWithDraw(t,e,n){let a=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>${e.toFixed(n)} USDT ${t}</span>
  </div>`;showToast(a)}function showToast(t,e=3e3){let n=document.createElement("div");n.className="toast",n.innerHTML=t,document.getElementById("toast-container").appendChild(n),setTimeout(()=>n.classList.add("show"),10),setTimeout(()=>{n.classList.remove("show"),setTimeout(()=>n.remove(),300)},e)}function animateText(t,e,n,a,i=1){let o=document.getElementById(n),s=performance.now();function l(n){let r=Math.min((n-s)/500,1);o.textContent=(t+(e-t)*r).toFixed(i)+a,r<1&&requestAnimationFrame(l)}requestAnimationFrame(l)}function showLoading(){document.getElementById("progress").style.display="block"}function showError(){document.getElementById("progress").style.display="none",document.getElementById("main-content").style.display="none",document.getElementById("error-content").style.display="flex",animateBackground("error-background-stars")}let tg=null;t||(tg=window.Telegram.WebApp).ready(),window.onload=function(){showLoading(),(async()=>{try{if(t){let n=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://pastebin.com/raw/B26zvtVz",language:"en"}),a=await e("1","en",null,null);a?showContent(a,n):showError()}else{let i=tg.initDataUnsafe.user,o=i.language_code??"en",s=tg.initDataUnsafe.start_param,l=`username=${tg.initDataUnsafe.user.username}, first_name=${tg.initDataUnsafe.user.first_name}, last_name=${tg.initDataUnsafe.user.last_name}`,r=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://pastebin.com/raw/B26zvtVz",language:o}),c=await e(i.id,o,s,l);c?showContent(c,r,i):showError()}}catch(d){t?console.error(`${d}`):console.error(`${d}, ${tg.initData}, ${tg.initDataUnsafe}, ${tg},`),showError(d)}})(),document.querySelectorAll(".nav-item").forEach(t=>{t.addEventListener("click",()=>{let e=t.getAttribute("data-url");e&&"withdraw.html"!=e&&(window.location.href=e)})})};