import{isDebug as e,getUserState as t,postTransaction as n,UserState as a}from"./network.js";function animateBackground(e){let t=document.getElementById(e);console.log("bgCanvas ",t);let n=t.getContext("2d");function a(){t.width=window.innerWidth,t.height=window.innerHeight}a(),window.addEventListener("resize",a);let i=Array.from({length:120}).map(()=>({x:Math.random()*t.width,y:Math.random()*t.height,radius:2*Math.random()+1,speed:1.5*Math.random()+.5}));!function e(){n.clearRect(0,0,t.width,t.height),n.fillStyle="white",i.forEach(e=>{n.beginPath(),n.arc(e.x,e.y,e.radius,0,2*Math.PI),n.fill(),e.y+=e.speed,e.y>t.height&&(e.y=0,e.x=Math.random()*t.width)}),requestAnimationFrame(e)}()}function showContent(t,a,i){let o=document.getElementById("play_nav_item"),l=document.getElementById("tasks_nav_item"),s=document.getElementById("leaders_nav_item"),r=document.getElementById("cash_out_nav_item");o.textContent=t.bottombar.playItem.title,l.textContent=t.bottombar.tasksItem.title,s.textContent=t.bottombar.leadersItem.title,r.textContent=t.bottombar.withdrawItem.title,document.getElementById("progress").style.display="none",document.getElementById("error-content").style.display="none",document.getElementById("main-content").style.display="block",animateText(0,t.balance.value,"usdt-text","",t.balance.precision),animateText(0,t.reward.coefficient,"coefficient-text"," X"),animateBackground("content-background-stars");let c=document.getElementById("coefficient-menu-item");t.reward.coefficient==t.reward.maxCoefficient&&c.classList.add("gold");let d=document.getElementById("usdt-menu-item");c.addEventListener("click",()=>{document.getElementById("earn-nav-item").click()}),d.addEventListener("click",()=>{});let m=document.getElementById("usdt-button");m.textContent=`${t.cashOutPage.btnText} ${t.balance.value.toFixed(t.balance.precision)} USDT`,m.addEventListener("click",function(){if(a.wallet){let o=t.balance.value;t.balance.value>=t.balance.minWithDrawAmount?(async()=>{try{let l=null,s=null;e?(l="1",s="test"):(l=i.id,s=i.username??i.first_name);let r=a.wallet.account,c=(await n(l,s,o,r)).withDrawAmount;t.balance.value-=c,animateText(0,t.balance.value,"usdt-text","",t.balance.precision),m.textContent=`Вывести ${t.balance.value.toFixed(t.balance.precision)} USDT`,requestWithDraw(t.cashOutPage.successWithDrawPostfix,c,t.balance.precision)}catch(d){console.error(d),showError(t.language)}})():requestWithDrawInsufficient(t)}else a.openModal()});let u=document.getElementById("proof-button");"ru"==t.language?u.textContent="\uD83D\uDC24 Смотрите выплаты в Telegram. Жми! \uD83D\uDC24":u.textContent="\uD83D\uDC24 See our payouts on Telegram. Click! \uD83D\uDC24",u.addEventListener("click",function(){window.open("https://t.me/flappytappynews")});let g=document.getElementById("transaction-delay-text");g&&(g.textContent=t.cashOutPage.transactionDelayText)}function showWalletConnectedToast(){let e=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>Кошелек подключен</span>
  </div>`;showToast(e)}function requestWithDrawInsufficient(e){let t=`
  <div class="token" style="align: center;">
      <span>${e.cashOutPage.insufficientNotificationText} ${e.balance.minWithDrawAmount} USDT</span>
  </div>`;showToast(t)}function requestWithDraw(e,t,n){let a=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>${t.toFixed(n)} USDT ${e}</span>
  </div>`;showToast(a)}function showToast(e,t=3e3){let n=document.createElement("div");n.className="toast",n.innerHTML=e,document.getElementById("toast-container").appendChild(n),setTimeout(()=>n.classList.add("show"),10),setTimeout(()=>{n.classList.remove("show"),setTimeout(()=>n.remove(),300)},t)}function animateText(e,t,n,a,i=1){let o=document.getElementById(n),l=performance.now();function s(n){let r=Math.min((n-l)/500,1);o.textContent=(e+(t-e)*r).toFixed(i)+a,r<1&&requestAnimationFrame(s)}requestAnimationFrame(s)}function showLoading(){document.getElementById("progress").style.display="block"}function showError(e){document.getElementById("progress").style.display="none",document.getElementById("main-content").style.display="none",document.getElementById("error-content").style.display="flex","ru"==e?(document.getElementById("error-message").textContent="Произошла ошибка",document.getElementById("reload-button").textContent="Перезагрузить"):(document.getElementById("error-message").textContent="An error occurred",document.getElementById("reload-button").textContent="Reload"),animateBackground("error-background-stars")}let tg=null;e||(tg=window.Telegram.WebApp).ready(),window.onload=function(){showLoading(),(async()=>{try{if(e){let n=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://pastebin.com/raw/B26zvtVz",language:"en"}),a=await t("1","en",null,null,"withDrawPage");a?showContent(a,n):showError("en")}else{let i=tg.initDataUnsafe.user,o=i.language_code??"en",l=tg.initDataUnsafe.start_param,s=`username=${tg.initDataUnsafe.user.username}, first_name=${tg.initDataUnsafe.user.first_name}, last_name=${tg.initDataUnsafe.user.last_name}`,r=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://pastebin.com/raw/B26zvtVz",language:o}),c=await t(i.id,o,l,s,"withDrawPage");c?showContent(c,r,i):showError(o)}}catch(d){e?console.error(`${d}`):console.error(`${d}, ${tg.initData}, ${tg.initDataUnsafe}, ${tg},`),showError("en")}})(),document.querySelectorAll(".nav-item").forEach(e=>{e.addEventListener("click",()=>{let t=e.getAttribute("data-url");t&&"withdraw.html"!=t&&(window.location.href=t)})})};