import{isDebug as t,getUserState as e,postTransaction as n,UserState as a}from"./network.js";function animateBackground(t){let e=document.getElementById(t);console.log("bgCanvas ",e);let n=e.getContext("2d");function a(){e.width=window.innerWidth,e.height=window.innerHeight}a(),window.addEventListener("resize",a);let i=Array.from({length:120}).map(()=>({x:Math.random()*e.width,y:Math.random()*e.height,radius:2*Math.random()+1,speed:1.5*Math.random()+.5}));!function t(){n.clearRect(0,0,e.width,e.height),n.fillStyle="white",i.forEach(t=>{n.beginPath(),n.arc(t.x,t.y,t.radius,0,2*Math.PI),n.fill(),t.y+=t.speed,t.y>e.height&&(t.y=0,t.x=Math.random()*e.width)}),requestAnimationFrame(t)}()}function showContent(e,a,i){let o=document.getElementById("play_nav_item"),l=document.getElementById("tasks_nav_item"),s=document.getElementById("leaders_nav_item"),r=document.getElementById("cash_out_nav_item");o.textContent=e.bottombar.playItem.title,l.textContent=e.bottombar.tasksItem.title,s.textContent=e.bottombar.leadersItem.title,r.textContent=e.bottombar.withdrawItem.title,document.getElementById("progress").style.display="none",document.getElementById("error-content").style.display="none",document.getElementById("main-content").style.display="block",animateText(0,e.balance.value,"usdt-text","",e.balance.precision),animateText(0,e.reward.coefficient,"coefficient-text"," X"),animateBackground("content-background-stars");let c=document.getElementById("coefficient-menu-item");e.reward.coefficient==e.reward.maxCoefficient&&c.classList.add("gold");let d=document.getElementById("usdt-menu-item");c.addEventListener("click",()=>{document.getElementById("earn-nav-item").click()}),d.addEventListener("click",()=>{});let m=document.getElementById("usdt-button");m.textContent=`${e.cashOutPage.btnText} ${e.balance.value.toFixed(e.balance.precision)} USDT`,m.addEventListener("click",function(){if(a.wallet){let o=e.balance.value;e.balance.value>=e.balance.minWithDrawAmount?(async()=>{try{let l=null,s=null;t?(l="1",s="test"):(l=i.id,s=i.username??i.first_name);let r=a.wallet.account,c=(await n(l,s,o,r)).withDrawAmount;e.balance.value-=c,animateText(0,e.balance.value,"usdt-text","",e.balance.precision),m.textContent=`Вывести ${e.balance.value.toFixed(e.balance.precision)} USDT`,requestWithDraw(e.cashOutPage.successWithDrawPostfix,c,e.balance.precision)}catch(d){console.error(d),showError(e.language)}})():requestWithDrawInsufficient(e)}else a.openModal()});let u=document.getElementById("proof-button");"ru"==e.language?u.textContent="\uD83D\uDC24 Смотрите выплаты в Telegram. Жми! \uD83D\uDC24":u.textContent="\uD83D\uDC24 See our payouts on Telegram. Click! \uD83D\uDC24",u.addEventListener("click",function(){window.open("https://t.me/flappytappynews")});let g=document.getElementById("transaction-delay-text");g&&(g.textContent=e.cashOutPage.transactionDelayText)}function showWalletConnectedToast(){let t=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>Кошелек подключен</span>
  </div>`;showToast(t)}function requestWithDrawInsufficient(t){let e=`
  <div class="token" style="align: center;">
      <span>${t.cashOutPage.insufficientNotificationText} ${t.balance.minWithDrawAmount} USDT</span>
  </div>`;showToast(e)}function requestWithDraw(t,e,n){let a=`
  <div class="token" style="align: center;">
      <span>✅</span>
      <span>${e.toFixed(n)} USDT ${t}</span>
  </div>`;showToast(a)}function showToast(t,e=3e3){let n=document.createElement("div");n.className="toast",n.innerHTML=t,document.getElementById("toast-container").appendChild(n),setTimeout(()=>n.classList.add("show"),10),setTimeout(()=>{n.classList.remove("show"),setTimeout(()=>n.remove(),300)},e)}function animateText(t,e,n,a,i=1){let o=document.getElementById(n),l=performance.now();function s(n){let r=Math.min((n-l)/500,1);o.textContent=(t+(e-t)*r).toFixed(i)+a,r<1&&requestAnimationFrame(s)}requestAnimationFrame(s)}function showLoading(){document.getElementById("progress").style.display="block"}function showError(t){document.getElementById("progress").style.display="none",document.getElementById("main-content").style.display="none",document.getElementById("error-content").style.display="flex","ru"==t?(document.getElementById("error-message").textContent="Произошла ошибка",document.getElementById("reload-button").textContent="Перезагрузить"):(document.getElementById("error-message").textContent="An error occurred",document.getElementById("reload-button").textContent="Reload"),animateBackground("error-background-stars")}let tg=null;t||(tg=window.Telegram.WebApp).ready(),window.onload=function(){showLoading(),(async()=>{try{if(t){let n=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://pastebin.com/raw/B26zvtVz",language:"en"}),a=await e("1","en",null,null,"withDrawPage",null);a?showContent(a,n):showError("en")}else{let i=tg.initDataUnsafe.user,o=i.language_code??"en",l=tg.initDataUnsafe.start_param,s=`username=${tg.initDataUnsafe.user.username}, first_name=${tg.initDataUnsafe.user.first_name}, last_name=${tg.initDataUnsafe.user.last_name}`,r=tg.initData,c=new TON_CONNECT_UI.TonConnectUI({manifestUrl:"https://sklych.github.io/door/tonconnect-manifest.json",language:o}),d=await e(i.id,o,l,s,"withDrawPage",r);d?showContent(d,c,i):showError(o)}}catch(m){t?console.error(`${m}`):console.error(`${m}, ${tg.initData}, ${tg.initDataUnsafe}, ${tg},`),showError("en")}})(),document.querySelectorAll(".nav-item").forEach(t=>{t.addEventListener("click",()=>{let e=t.getAttribute("data-url");e&&"withdraw.html"!=e&&(window.location.href=e)})})};